name: Build OCI Management App and Sphinx Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Installs dependencies from pyproject.toml
          pip install sphinx sphinx-rtd-theme  # Sphinx and theme for docs

      - name: Build with PyInstaller
        run: python build.py

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: oci-management-app-${{ matrix.os }}
          path: dist/main*
